version: "3"

volumes:
  mongodb_volume:

services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_volume:/data/db
    environment:
      MONGO_INITDB_DATABASE: chat

  chat:
    build: ./
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mongodb
